package springboot.b2b.shop.dao;

import springboot.b2b.shop.DTO.UserPassword;

public interface UserPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Sep 18 21:49:01 CST 2019
     */
    int insert(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Sep 18 21:49:01 CST 2019
     */
    int insertSelective(UserPassword record);
}