package springboot.b2b.shop.dao;

import org.apache.catalina.User;
import org.apache.ibatis.annotations.MapKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import springboot.b2b.shop.DTO.UserInfo;

import java.util.Map;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Sep 18 21:49:01 CST 2019
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Sep 18 21:49:01 CST 2019
     */
    int insertSelective(UserInfo record);

    UserInfo selectByPrimaryKey(Integer id);
    UserInfo selectByIDAndNae(@Param("xx") Integer id,@Param("ww") String name);

    @MapKey("id")
    Map<Integer,UserInfo> selectByName(String name);
}